/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author rufino
 */
@StyleSheet
@Template(CrudFormPage.class)
public class HRMISAppointmentPermanentCRUDPage extends javax.swing.JPanel {

    /**
     * Creates new form HRMISAppointmentCasualCRUDPage
     */
    public HRMISAppointmentPermanentCRUDPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xScrollPane1 = new com.rameses.rcp.control.XScrollPane();
        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLookupField11 = new com.rameses.rcp.control.XLookupField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xLookupField8 = new com.rameses.rcp.control.XLookupField();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        xLookupField9 = new com.rameses.rcp.control.XLookupField();
        xLookupField10 = new com.rameses.rcp.control.XLookupField();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xDateField6 = new com.rameses.rcp.control.XDateField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField7 = new com.rameses.rcp.control.XDateField();
        xDateField8 = new com.rameses.rcp.control.XDateField();
        xDateField9 = new com.rameses.rcp.control.XDateField();
        xDateField10 = new com.rameses.rcp.control.XDateField();
        jPanel4 = new javax.swing.JPanel();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setPreferredSize(new java.awt.Dimension(780, 1280));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Appointment Details");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionWidth(160);
        xFormPanel1.setName(""); // NOI18N
        xFormPanel1.setPreferredSize(new java.awt.Dimension(500, 100));

        xLabel1.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel1.setCaption("Doc No.");
        xLabel1.setExpression("#{entity.appno}");
        xLabel1.setOpaque(true);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel1);

        xLookupField11.setCaption("Employee Name");
        xLookupField11.setExpression("#{(item.prenametitle == '' ||  !item.prenametitle ?'': item.prenametitle + ' ') + item.person.name + (item.nameextension=='' || !item.nameextension?'' :' ' + item.nameextension)}");
        xLookupField11.setHandler("lookup:tagabukid_hrmis_pds");
        xLookupField11.setName("entity.pds"); // NOI18N
        xLookupField11.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField11.setRequired(true);
        xFormPanel1.add(xLookupField11);

        xTextField7.setCaption("Pre Name Title");
        xTextField7.setCaptionWidth(160);
        xTextField7.setDepends(new String[] {"entity.pds"});
        xTextField7.setName("entity.pds.prenametitle"); // NOI18N
        xTextField7.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel1.add(xTextField7);

        xTextField6.setCaption("Post Name Title");
        xTextField6.setCaptionWidth(160);
        xTextField6.setDepends(new String[] {"entity.pds"});
        xTextField6.setName("entity.pds.postnametitle"); // NOI18N
        xTextField6.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel1.add(xTextField6);

        xTextField5.setCaption("Extension (Jr., Sr)");
        xTextField5.setCaptionWidth(160);
        xTextField5.setDepends(new String[] {"entity.pds"});
        xTextField5.setName("entity.pds.nameextension"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel1.add(xTextField5);

        xDateField1.setCaption("Effective From");
        xDateField1.setName("entity.effectivefrom"); // NOI18N
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Effective Until");
        xDateField2.setName("entity.effectiveuntil"); // NOI18N
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xLookupField8.setCaption("Status");
        xLookupField8.setExpression("#{item.name}");
        xLookupField8.setHandler("lookup:tagabukid_hrmis_employmentstatus");
        xLookupField8.setName("entity.status"); // NOI18N
        xLookupField8.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField8.setRequired(true);
        xFormPanel1.add(xLookupField8);

        xLookupField4.setCaption("Nature of Appointment");
        xLookupField4.setExpression("#{item.name}");
        xLookupField4.setHandler("lookup:tagabukid_hrmis_natureofappointment");
        xLookupField4.setName("entity.natureofappointment"); // NOI18N
        xLookupField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField4.setRequired(true);
        xFormPanel1.add(xLookupField4);

        xLookupField9.setCaption("Org Unit");
        xLookupField9.setEnabled(false);
        xLookupField9.setExpression("#{item.name}");
        xLookupField9.setHandler("lookup:tagabukid_hrmis_org");
        xLookupField9.setName("entity.org"); // NOI18N
        xLookupField9.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField9.setRequired(true);
        xLookupField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xLookupField9ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xLookupField9);

        xLookupField10.setCaption("Plantilla Info");
        xLookupField10.setExpression("#{item.jobposition.name + ' |  Item No. ' + item.itemno}");
        xLookupField10.setHandler("lookup:tagabukid_hrmis_vacantpermanentplantilla");
        xLookupField10.setName("entity.plantilla"); // NOI18N
        xLookupField10.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField10.setRequired(true);
        xFormPanel1.add(xLookupField10);

        xLabel2.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel2.setCaption("Salary Grade and Step Inc.");
        xLabel2.setExpression("#{'Grade - ' + item.grade + ' | Step - ' + item.step}");
        xLabel2.setName("entity.paygradeandstepincrement"); // NOI18N
        xLabel2.setOpaque(true);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel2);

        xDateField4.setCaption("Focal date of increment");
        xDateField4.setName("entity.dateissued"); // NOI18N
        xDateField4.setRequired(true);
        xFormPanel1.add(xDateField4);

        xDecimalField1.setCaption("Compensation");
        xDecimalField1.setName("entity.compensation"); // NOI18N
        xFormPanel1.add(xDecimalField1);

        xDateField3.setCaption("Date Issued");
        xDateField3.setName("entity.dateissued"); // NOI18N
        xDateField3.setRequired(true);
        xFormPanel1.add(xDateField3);

        xTextField3.setCaption("Succeeded Person");
        xTextField3.setName("entity.succeededperson"); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField3);

        xTextField4.setCaption("Cause of Succession");
        xTextField4.setName("entity.casueofsuccession"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField4);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Certification Details");
        xFormPanel2.setBorder(xTitledBorder2);
        xFormPanel2.setCaptionWidth(160);
        xFormPanel2.setPreferredSize(new java.awt.Dimension(500, 100));

        xTextField1.setCaption("Position published (location)");
        xTextField1.setName("entity.positionpublishedlocation"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xTextField1);

        xDateField5.setCaption("Position published from");
        xDateField5.setName("entity.positionpublishedlocationdatefrom"); // NOI18N
        xDateField5.setRequired(true);
        xFormPanel2.add(xDateField5);

        xDateField6.setCaption("Position published to");
        xDateField6.setName("entity.positionpublishedlocationdateto"); // NOI18N
        xDateField6.setRequired(true);
        xFormPanel2.add(xDateField6);

        xTextField2.setCaption("Position posted in (location)");
        xTextField2.setName("entity.positionpostedlocation"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xTextField2);

        xDateField7.setCaption("Position posted from");
        xDateField7.setName("entity.positionpostedlocationdatefrom"); // NOI18N
        xDateField7.setRequired(true);
        xFormPanel2.add(xDateField7);

        xDateField8.setCaption("Position posted to");
        xDateField8.setName("entity.positionpostedlocationdateto"); // NOI18N
        xDateField8.setRequired(true);
        xFormPanel2.add(xDateField8);

        xDateField9.setCaption("Assessment date start");
        xDateField9.setName("entity.assessmentdatestart"); // NOI18N
        xDateField9.setRequired(true);
        xFormPanel2.add(xDateField9);

        xDateField10.setCaption("Deliberation date");
        xDateField10.setName("entity.deliberationdate"); // NOI18N
        xDateField10.setRequired(true);
        xFormPanel2.add(xDateField10);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Signatory Details");
        jPanel4.setBorder(xTitledBorder3);
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 100));

        xDataTable3.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "signatoryname"}
                , new Object[]{"caption", "Signatory Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "signatorytitle"}
                , new Object[]{"caption", "Signatory Title"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "org"}
                , new Object[]{"caption", "Office"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "signatoryheading"}
                , new Object[]{"caption", "Heading"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "level"}
                , new Object[]{"caption", "Level"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable3.setDepends(new String[] {"entity.signatorygroup"});
        xDataTable3.setDynamic(true);
        xDataTable3.setHandler("signatoryItemHandler");
        xDataTable3.setName("selectedSignaotryItem"); // NOI18N

        xFormPanel6.setPreferredSize(new java.awt.Dimension(500, 100));

        xLookupField3.setCaption("Signatory Group");
        xLookupField3.setCaptionWidth(100);
        xLookupField3.setExpression("#{item.signatorygroupname}");
        xLookupField3.setHandler("signatorygroup:lookup");
        xLookupField3.setName("entity.signatorygroup"); // NOI18N
        xLookupField3.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel6.add(xLookupField3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xDataTable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDataTable3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Transaction Info");
        xFormPanel5.setBorder(xTitledBorder4);
        xFormPanel5.setPreferredSize(new java.awt.Dimension(500, 100));

        jScrollPane2.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 40));

        xTextArea2.setEditable(false);
        xTextArea2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xTextArea2.setForeground(new java.awt.Color(204, 0, 0));
        xTextArea2.setName("entity.state"); // NOI18N
        xTextArea2.setShowCaption(false);
        jScrollPane2.setViewportView(xTextArea2);

        xFormPanel5.add(jScrollPane2);

        xLabel7.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel7.setCaption("Created By");
        xLabel7.setExpression("#{entity.recordlog.createdbyuser}");
        xLabel7.setFor("");
        xLabel7.setName(""); // NOI18N
        xLabel7.setOpaque(true);
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel5.add(xLabel7);

        xLabel4.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel4.setCaption("Date Created");
        xLabel4.setExpression("#{entity.recordlog.datecreated}");
        xLabel4.setFor("");
        xLabel4.setOpaque(true);
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel5.add(xLabel4);

        xLabel8.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel8.setCaption("Updated  By");
        xLabel8.setExpression("#{entity.recordlog.lastupdatedbyuser}");
        xLabel8.setFor("");
        xLabel8.setName(""); // NOI18N
        xLabel8.setOpaque(true);
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel5.add(xLabel8);

        xLabel9.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel9.setCaption("Date Updated");
        xLabel9.setExpression("#{entity.recordlog.dateupdated}");
        xLabel9.setFor("");
        xLabel9.setName(""); // NOI18N
        xLabel9.setOpaque(true);
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel5.add(xLabel9);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 63));

        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("entity.remarks"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel5.add(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        xScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1266, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xLookupField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xLookupField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xLookupField9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField10;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XDateField xDateField6;
    private com.rameses.rcp.control.XDateField xDateField7;
    private com.rameses.rcp.control.XDateField xDateField8;
    private com.rameses.rcp.control.XDateField xDateField9;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField10;
    private com.rameses.rcp.control.XLookupField xLookupField11;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XLookupField xLookupField8;
    private com.rameses.rcp.control.XLookupField xLookupField9;
    private com.rameses.rcp.control.XScrollPane xScrollPane1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    // End of variables declaration//GEN-END:variables
}
