/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author user
 */
@StyleSheet
@Template(CrudFormPage.class)
public class LeavePersonalInfoPage extends javax.swing.JPanel {

    /**
     * Creates new form PDSPersonalInfoNewPage
     */
    public LeavePersonalInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xHorizontalPanel1 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        civilStatusList1 = new com.rameses.enterprise.components.CivilStatusList();
        genderList1 = new com.rameses.enterprise.components.GenderList();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Personal");
        xHorizontalPanel1.setBorder(xTitledBorder1);

        entityLookup1.setCaption("Name");
        entityLookup1.setCaptionWidth(135);
        entityLookup1.setExpression("#{entity.name}");
        entityLookup1.setName("entity.person"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(entityLookup1);

        xTextField1.setText("entity.maidenname");
        xTextField1.setCaption("Maiden Name");
        xTextField1.setCaptionWidth(135);
        xTextField1.setName("entity.maidenname"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel1.add(xTextField1);
        xTextField1.getAccessibleContext().setAccessibleName("Maiden Name:");

        xTextField4.setCaption("Extension (Jr., Sr)");
        xTextField4.setCaptionWidth(135);
        xTextField4.setName("entity.nameextension"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel1.add(xTextField4);

        xDateField1.setCaption("Date of Birth");
        xDateField1.setCaptionWidth(135);
        xDateField1.setDepends(new String[] {"entity.person"});
        xDateField1.setName("entity.person.birthdate"); // NOI18N
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        civilStatusList1.setCaption("Civil Status");
        civilStatusList1.setCaptionWidth(135);
        civilStatusList1.setDepends(new String[] {"entity.person"});
        civilStatusList1.setName("entity.person.civilstatus"); // NOI18N
        civilStatusList1.setRequired(true);
        xFormPanel1.add(civilStatusList1);

        genderList1.setCaption("Gender");
        genderList1.setCaptionWidth(135);
        genderList1.setDepends(new String[] {"entity.person"});
        genderList1.setName("entity.person.gender"); // NOI18N
        genderList1.setRequired(true);
        xFormPanel1.add(genderList1);

        xHorizontalPanel1.add(xFormPanel1);

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 979, Short.MAX_VALUE))
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(xPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.CivilStatusList civilStatusList1;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.enterprise.components.GenderList genderList1;
    private javax.swing.JScrollPane jScrollPane4;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField4;
    // End of variables declaration//GEN-END:variables
}
