/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author BlackHat
 */
@StyleSheet
//@Template({FormPage.class})
@Template(CrudFormPage.class)
public class PDSInfoNewPage extends javax.swing.JPanel {

    /**
     * Creates new form PDSPersonalInfoView
     */
    public PDSInfoNewPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xTextFieldBeanInfo1 = new com.rameses.rcp.control.XTextFieldBeanInfo();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xDateFieldBeanInfo1 = new com.rameses.rcp.control.XDateFieldBeanInfo();
        xFormPanelBeanInfo1 = new com.rameses.rcp.control.XFormPanelBeanInfo();
        xComboBoxBeanInfo1 = new com.rameses.rcp.control.XComboBoxBeanInfo();
        xFormPanelBeanInfo2 = new com.rameses.rcp.control.XFormPanelBeanInfo();
        xFormPanelBeanInfo3 = new com.rameses.rcp.control.XFormPanelBeanInfo();
        xTextAreaBeanInfo1 = new com.rameses.rcp.control.XTextAreaBeanInfo();
        xPhoto1 = new com.rameses.rcp.control.XPhoto();
        xHorizontalPanel1 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();

        setDoubleBuffered(false);

        xPhoto1.setDepends(new String[] {"entity.person"});
        xPhoto1.setName("entity.person.photo"); // NOI18N
        xPhoto1.setText("xPhoto1");

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Person Info");
        xHorizontalPanel1.setBorder(xTitledBorder1);

        entityLookup1.setCaption("Name");
        entityLookup1.setCaptionWidth(135);
        entityLookup1.setExpression("#{item.name}");
        entityLookup1.setName("entity.person"); // NOI18N
        entityLookup1.setRequired(true);
        entityLookup1.setStretchWidth(300);
        xFormPanel1.add(entityLookup1);

        xHorizontalPanel1.add(xFormPanel1);
        xFormPanel1.getAccessibleContext().setAccessibleParent(xFormPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(xPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.rcp.control.XComboBoxBeanInfo xComboBoxBeanInfo1;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDateFieldBeanInfo xDateFieldBeanInfo1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanelBeanInfo xFormPanelBeanInfo1;
    private com.rameses.rcp.control.XFormPanelBeanInfo xFormPanelBeanInfo2;
    private com.rameses.rcp.control.XFormPanelBeanInfo xFormPanelBeanInfo3;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel1;
    private com.rameses.rcp.control.XPhoto xPhoto1;
    private com.rameses.rcp.control.XTextAreaBeanInfo xTextAreaBeanInfo1;
    private com.rameses.rcp.control.XTextFieldBeanInfo xTextFieldBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
