/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author PORA
 */
@StyleSheet
@Template(CrudFormPage.class)
public class PDSQuestionPage extends javax.swing.JPanel {

    /**
     * Creates new form PDSQuestionPage
     */
    public PDSQuestionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xScrollPane1 = new com.rameses.rcp.control.XScrollPane();
        xHorizontalPanel1 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xRadioList1 = new com.rameses.rcp.control.XRadioList();
        xRadioList2 = new com.rameses.rcp.control.XRadioList();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xRadioList3 = new com.rameses.rcp.control.XRadioList();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xRadioList4 = new com.rameses.rcp.control.XRadioList();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        xRadioList5 = new com.rameses.rcp.control.XRadioList();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        xRadioList6 = new com.rameses.rcp.control.XRadioList();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xSeparator4 = new com.rameses.rcp.control.XSeparator();
        xRadioList7 = new com.rameses.rcp.control.XRadioList();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xRadioList8 = new com.rameses.rcp.control.XRadioList();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xSeparator5 = new com.rameses.rcp.control.XSeparator();
        xRadioList9 = new com.rameses.rcp.control.XRadioList();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xSeparator6 = new com.rameses.rcp.control.XSeparator();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xRadioList10 = new com.rameses.rcp.control.XRadioList();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xRadioList11 = new com.rameses.rcp.control.XRadioList();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xRadioList12 = new com.rameses.rcp.control.XRadioList();
        xTextField13 = new com.rameses.rcp.control.XTextField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("PDS Questions");
        xHorizontalPanel1.setBorder(xTitledBorder1);

        xLabel2.setCaption("");
        xLabel2.setPreferredSize(new java.awt.Dimension(500, 50));
        xLabel2.setShowCaption(false);
        xLabel2.setText("Are you related by consanguinity or affinity to the appointing or recommending authority, or to the chief of bureau or office or to the person who has immediate supervision over you in the Office, Bureau or Department where you will be apppointed,");
        xLabel2.setUseHtml(true);
        xFormPanel1.add(xLabel2);

        xRadioList1.setCaption("a. within the third degree?");
        xRadioList1.setCaptionWidth(725);
        xRadioList1.setHandler("choice");
        xRadioList1.setItemGap(50);
        xRadioList1.setName("entity.thirddegree"); // NOI18N
        xFormPanel1.add(xRadioList1);

        xRadioList2.setCaption("b. within the fourth degree (for Local Government Unit - Career Employees)?");
        xRadioList2.setCaptionWidth(725);
        xRadioList2.setItemGap(50);
        xRadioList2.setName("entity.fourthdegree"); // NOI18N
        xFormPanel1.add(xRadioList2);

        xTextField1.setCaption("If YES, give details");
        xTextField1.setCaptionWidth(110);
        xTextField1.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField1.setName("entity.degreedetails"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField1);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator1);

        xRadioList3.setCaption("a. Have you ever been found guilty of any administrative offense?");
        xRadioList3.setCaptionWidth(725);
        xRadioList3.setHandler("choiceHandler");
        xRadioList3.setItemExpression("");
        xRadioList3.setItemGap(50);
        xRadioList3.setName("entity.offense"); // NOI18N
        xFormPanel1.add(xRadioList3);

        xTextField4.setCaption("If YES, give details");
        xTextField4.setCaptionWidth(110);
        xTextField4.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField4.setName("entity.offensedetails"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField4);

        xRadioList4.setCaption("b. Have you been criminally charged before any court?");
        xRadioList4.setCaptionWidth(725);
        xRadioList4.setItemGap(50);
        xRadioList4.setName("entity.criminalcharge"); // NOI18N
        xFormPanel1.add(xRadioList4);

        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xLabel1.setCaption(" ");
        xLabel1.setCaptionWidth(700);
        xLabel1.setText(" If YES, give details:");
        xFormPanel1.add(xLabel1);

        xDateField2.setCaption("Date Filed");
        xDateField2.setCaptionWidth(110);
        xDateField2.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xDateField2.setName("entity.criminalchargedate"); // NOI18N
        xDateField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xDateField2);

        xTextField5.setCaption("Status of Case/s");
        xTextField5.setCaptionWidth(110);
        xTextField5.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField5.setName("entity.criminalchargestatus"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField5);

        xSeparator3.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator3);

        xRadioList5.setCaption("Have you ever been convicted of any crime or violation of any law, decree, ordinance or regulation\n by any court or tribunal?");
        xRadioList5.setCaptionWidth(725);
        xRadioList5.setItemGap(50);
        xRadioList5.setName("entity.convicted"); // NOI18N
        xFormPanel1.add(xRadioList5);

        xTextField6.setCaption("If YES, give details");
        xTextField6.setCaptionWidth(110);
        xTextField6.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField6.setName("entity.convictiondetails"); // NOI18N
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField6);

        xSeparator2.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator2);

        xRadioList6.setCaption("Have you ever been separated from the service in any of the following modes: resignation, retirement, dropped from the rolls, dismissal, termination, end of term, finished contract or phased out (abolition) in the public or private sector?");
        xRadioList6.setCaptionWidth(725);
        xRadioList6.setItemGap(50);
        xRadioList6.setName("entity.separated"); // NOI18N
        xFormPanel1.add(xRadioList6);

        xTextField7.setCaption("If YES, give details");
        xTextField7.setCaptionWidth(110);
        xTextField7.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField7.setName("entity.separationdetails"); // NOI18N
        xTextField7.setNullWhenEmpty(false);
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField7);

        xSeparator4.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator4);

        xRadioList7.setCaption("a. Have you ever been a candidate in a national or local election held within the last year (except Barangay election)?");
        xRadioList7.setCaptionWidth(725);
        xRadioList7.setItemGap(50);
        xRadioList7.setName("entity.candidate"); // NOI18N
        xFormPanel1.add(xRadioList7);

        xTextField8.setCaption("If YES, give details");
        xTextField8.setCaptionWidth(110);
        xTextField8.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField8.setName("entity.candidacydetails"); // NOI18N
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField8);

        xRadioList8.setCaption("b. Have you resigned from the government service during the three (3)-month period before the last election to promote/actively campaign for a national or local candidate?");
        xRadioList8.setCaptionWidth(725);
        xRadioList8.setItemGap(50);
        xRadioList8.setName("entity.resigncampaign"); // NOI18N
        xFormPanel1.add(xRadioList8);

        xTextField9.setCaption("If YES, give details");
        xTextField9.setCaptionWidth(110);
        xTextField9.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField9.setName("entity.resigncampaigndetails"); // NOI18N
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField9);

        xSeparator5.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator5);

        xRadioList9.setCaption("Have you acquired the status of an immigrant or permanent resident of another country? ");
        xRadioList9.setCaptionWidth(725);
        xRadioList9.setItemGap(50);
        xRadioList9.setName("entity.immigrant"); // NOI18N
        xFormPanel1.add(xRadioList9);

        xLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xLabel3.setCaption(" ");
        xLabel3.setCaptionWidth(700);
        xLabel3.setExpression(" If YES, give details (country):");
        xFormPanel1.add(xLabel3);

        xTextField10.setCaption("If YES, give details");
        xTextField10.setCaptionWidth(110);
        xTextField10.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField10.setName("entity.immigrantcountry"); // NOI18N
        xTextField10.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField10.setShowCaption(false);
        xFormPanel1.add(xTextField10);

        xSeparator6.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel1.add(xSeparator6);

        xLabel4.setCaption("");
        xLabel4.setPreferredSize(new java.awt.Dimension(500, 50));
        xLabel4.setShowCaption(false);
        xLabel4.setText("Pursuant to: (a) Indigenous People's Act (RA 8371); (b) Magna Carta for Disabled Persons (RA 7277); and (c) Solo Parents Welfare Act of 2000 (RA 8972), please answer the following items:");
        xLabel4.setUseHtml(true);
        xFormPanel1.add(xLabel4);

        xRadioList10.setCaption("a. Are you a member of any indigenous group?");
        xRadioList10.setCaptionWidth(725);
        xRadioList10.setItemGap(50);
        xRadioList10.setName("entity.indigenousgroup"); // NOI18N
        xFormPanel1.add(xRadioList10);

        xTextField11.setCaption("If YES, please specify");
        xTextField11.setCaptionWidth(120);
        xTextField11.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField11.setName("entity.indigenousgroupdetails"); // NOI18N
        xTextField11.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField11);

        xRadioList11.setCaption("b. Are you a person with disability?");
        xRadioList11.setCaptionWidth(725);
        xRadioList11.setItemGap(50);
        xRadioList11.setName("entity.pwd"); // NOI18N
        xFormPanel1.add(xRadioList11);

        xTextField12.setCaption("If YES, please specify ID No");
        xTextField12.setCaptionWidth(150);
        xTextField12.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField12.setName("entity.pwdidno"); // NOI18N
        xTextField12.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField12);

        xRadioList12.setCaption("c. Are you a solo parent?");
        xRadioList12.setCaptionWidth(725);
        xRadioList12.setItemGap(50);
        xRadioList12.setName("entity.soloparent"); // NOI18N
        xFormPanel1.add(xRadioList12);

        xTextField13.setCaption("If YES, please specify ID No");
        xTextField13.setCaptionWidth(150);
        xTextField13.setCellPadding(new java.awt.Insets(0, 700, 0, 0));
        xTextField13.setName("entity.soloparentidno"); // NOI18N
        xTextField13.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField13);

        xHorizontalPanel1.add(xFormPanel1);

        xScrollPane1.setViewportView(xHorizontalPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XRadioList xRadioList1;
    private com.rameses.rcp.control.XRadioList xRadioList10;
    private com.rameses.rcp.control.XRadioList xRadioList11;
    private com.rameses.rcp.control.XRadioList xRadioList12;
    private com.rameses.rcp.control.XRadioList xRadioList2;
    private com.rameses.rcp.control.XRadioList xRadioList3;
    private com.rameses.rcp.control.XRadioList xRadioList4;
    private com.rameses.rcp.control.XRadioList xRadioList5;
    private com.rameses.rcp.control.XRadioList xRadioList6;
    private com.rameses.rcp.control.XRadioList xRadioList7;
    private com.rameses.rcp.control.XRadioList xRadioList8;
    private com.rameses.rcp.control.XRadioList xRadioList9;
    private com.rameses.rcp.control.XScrollPane xScrollPane1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XSeparator xSeparator4;
    private com.rameses.rcp.control.XSeparator xSeparator5;
    private com.rameses.rcp.control.XSeparator xSeparator6;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
