/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author pictd-training1
 */
@StyleSheet
@Template(CrudFormPage.class)
public class VerificationPage extends javax.swing.JPanel {

    /**
     * Creates new form PDSVerificationPage
     */
    public VerificationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xScrollPane1 = new com.rameses.rcp.control.XScrollPane();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLookupField5 = new com.rameses.rcp.control.XLookupField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        xLookupField6 = new com.rameses.rcp.control.XLookupField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xPanel3 = new com.rameses.rcp.control.XPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField7 = new com.rameses.rcp.control.XLookupField();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField14 = new com.rameses.rcp.control.XTextField();
        xFormPanel8 = new com.rameses.rcp.control.XFormPanel();
        xLookupField8 = new com.rameses.rcp.control.XLookupField();
        xTextField15 = new com.rameses.rcp.control.XTextField();
        xTextField16 = new com.rameses.rcp.control.XTextField();
        xPanel4 = new com.rameses.rcp.control.XPanel();
        xFormPanel9 = new com.rameses.rcp.control.XFormPanel();
        xLookupField9 = new com.rameses.rcp.control.XLookupField();
        xTextField17 = new com.rameses.rcp.control.XTextField();
        xTextField18 = new com.rameses.rcp.control.XTextField();
        xFormPanel10 = new com.rameses.rcp.control.XFormPanel();
        xLookupField10 = new com.rameses.rcp.control.XLookupField();
        xTextField19 = new com.rameses.rcp.control.XTextField();
        xTextField20 = new com.rameses.rcp.control.XTextField();
        xPanel5 = new com.rameses.rcp.control.XPanel();
        xPanel6 = new com.rameses.rcp.control.XPanel();
        xFormPanel11 = new com.rameses.rcp.control.XFormPanel();
        xLookupField11 = new com.rameses.rcp.control.XLookupField();
        xTextField21 = new com.rameses.rcp.control.XTextField();
        xTextField22 = new com.rameses.rcp.control.XTextField();
        xFormPanel12 = new com.rameses.rcp.control.XFormPanel();
        xLookupField12 = new com.rameses.rcp.control.XLookupField();
        xTextField23 = new com.rameses.rcp.control.XTextField();
        xTextField24 = new com.rameses.rcp.control.XTextField();
        xPanel7 = new com.rameses.rcp.control.XPanel();
        xFormPanel13 = new com.rameses.rcp.control.XFormPanel();
        xLookupField13 = new com.rameses.rcp.control.XLookupField();
        xTextField25 = new com.rameses.rcp.control.XTextField();
        xTextField26 = new com.rameses.rcp.control.XTextField();
        xFormPanel14 = new com.rameses.rcp.control.XFormPanel();
        xLookupField14 = new com.rameses.rcp.control.XLookupField();
        xTextField27 = new com.rameses.rcp.control.XTextField();
        xTextField28 = new com.rameses.rcp.control.XTextField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Applicant's Name");
        xFormPanel2.setBorder(xTitledBorder1);
        xFormPanel2.setCaption("");
        xFormPanel2.setCellspacing(10);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField1.setCaption("First Name");
        xLookupField1.setExpression("#{item.firstname}");
        xLookupField1.setHandler("lookup:individualwide");
        xLookupField1.setName("entity.person"); // NOI18N
        xFormPanel2.add(xLookupField1);

        xTextField2.setCaption("Middle Name");
        xTextField2.setDepends(new String[] {"entity.person"});
        xTextField2.setName("person.middlename"); // NOI18N
        xFormPanel2.add(xTextField2);

        xTextField1.setCaption("Last Name");
        xTextField1.setDepends(new String[] {"entity.person"});
        xTextField1.setName("person.lastname"); // NOI18N
        xFormPanel2.add(xTextField1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Spouse's Name (Maiden Name)");
        xFormPanel3.setBorder(xTitledBorder2);
        xFormPanel3.setCellspacing(10);
        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField2.setText("xLookupField1");
        xLookupField2.setCaption("First Name");
        xFormPanel3.add(xLookupField2);

        xTextField4.setText("xTextField2");
        xTextField4.setCaption("Middle Name");
        xFormPanel3.add(xTextField4);

        xTextField3.setText("xTextField1");
        xTextField3.setCaption("Last Name");
        xFormPanel3.add(xTextField3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Father's Name");
        xFormPanel4.setBorder(xTitledBorder3);
        xFormPanel4.setCellspacing(10);
        xFormPanel4.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField3.setText("xLookupField1");
        xLookupField3.setCaption("First Name");
        xFormPanel4.add(xLookupField3);

        xTextField6.setText("xTextField2");
        xTextField6.setCaption("Middle Name");
        xFormPanel4.add(xTextField6);

        xTextField5.setText("xTextField1");
        xTextField5.setCaption("Last Name");
        xFormPanel4.add(xTextField5);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Mother's Maiden Name");
        xFormPanel5.setBorder(xTitledBorder4);
        xFormPanel5.setCellspacing(10);
        xFormPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField4.setText("xLookupField1");
        xLookupField4.setCaption("First Name");
        xFormPanel5.add(xLookupField4);

        xTextField8.setText("xTextField2");
        xTextField8.setCaption("Middle Name");
        xFormPanel5.add(xTextField8);

        xTextField7.setText("xTextField1");
        xTextField7.setCaption("Last Name");
        xFormPanel5.add(xTextField7);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder5 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder5.setTitle("Spouse's Father");
        xFormPanel6.setBorder(xTitledBorder5);
        xFormPanel6.setCellspacing(10);
        xFormPanel6.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField5.setText("xLookupField1");
        xLookupField5.setCaption("First Name");
        xFormPanel6.add(xLookupField5);

        xTextField9.setText("xTextField1");
        xTextField9.setCaption("Middle Name");
        xFormPanel6.add(xTextField9);

        xTextField10.setText("xTextField2");
        xTextField10.setCaption("Last Name");
        xFormPanel6.add(xTextField10);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder6 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder6.setTitle("Spouse's Mother (Maiden Name)");
        xFormPanel7.setBorder(xTitledBorder6);
        xFormPanel7.setCellspacing(10);
        xFormPanel7.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField6.setText("xLookupField1");
        xLookupField6.setCaption("First Name");
        xFormPanel7.add(xLookupField6);

        xTextField11.setText("xTextField1");
        xTextField11.setCaption("Middle Name");
        xFormPanel7.add(xTextField11);

        xTextField12.setText("xTextField2");
        xTextField12.setCaption("Last Name");
        xFormPanel7.add(xTextField12);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder7 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder7.setTitle("GRANDPARENTS (Applicant)");
        xPanel2.setBorder(xTitledBorder7);

        xPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mother's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder8 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder8.setTitle("Lolo");
        xFormPanel1.setBorder(xTitledBorder8);
        xFormPanel1.setCellspacing(10);
        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField7.setText("xLookupField7");
        xLookupField7.setCaption("First Name");
        xFormPanel1.add(xLookupField7);

        xTextField13.setText("xTextField13");
        xTextField13.setCaption("Middle Name");
        xFormPanel1.add(xTextField13);

        xTextField14.setText("xTextField14");
        xTextField14.setCaption("Last Name");
        xFormPanel1.add(xTextField14);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder9 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder9.setTitle("Lola (Maiden Name)");
        xFormPanel8.setBorder(xTitledBorder9);
        xFormPanel8.setCellspacing(10);
        xFormPanel8.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField8.setText("xLookupField7");
        xLookupField8.setCaption("First Name");
        xFormPanel8.add(xLookupField8);

        xTextField15.setText("xTextField13");
        xTextField15.setCaption("Middle Name");
        xFormPanel8.add(xTextField15);

        xTextField16.setText("xTextField14");
        xTextField16.setCaption("Last Name");
        xFormPanel8.add(xTextField16);

        javax.swing.GroupLayout xPanel3Layout = new javax.swing.GroupLayout(xPanel3);
        xPanel3.setLayout(xPanel3Layout);
        xPanel3Layout.setHorizontalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(xFormPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        xPanel3Layout.setVerticalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        xPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Father's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder10 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder10.setTitle("Lolo");
        xFormPanel9.setBorder(xTitledBorder10);
        xFormPanel9.setCellspacing(10);
        xFormPanel9.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField9.setText("xLookupField7");
        xLookupField9.setCaption("First Name");
        xFormPanel9.add(xLookupField9);

        xTextField17.setText("xTextField13");
        xTextField17.setCaption("Middle Name");
        xFormPanel9.add(xTextField17);

        xTextField18.setText("xTextField14");
        xTextField18.setCaption("Last Name");
        xFormPanel9.add(xTextField18);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder11 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder11.setTitle("Lola (Maiden Name)");
        xFormPanel10.setBorder(xTitledBorder11);
        xFormPanel10.setCellspacing(10);
        xFormPanel10.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField10.setText("xLookupField7");
        xLookupField10.setCaption("First Name");
        xFormPanel10.add(xLookupField10);

        xTextField19.setText("xTextField13");
        xTextField19.setCaption("Middle Name");
        xFormPanel10.add(xTextField19);

        xTextField20.setText("xTextField14");
        xTextField20.setCaption("Last Name");
        xFormPanel10.add(xTextField20);

        javax.swing.GroupLayout xPanel4Layout = new javax.swing.GroupLayout(xPanel4);
        xPanel4.setLayout(xPanel4Layout);
        xPanel4Layout.setHorizontalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        xPanel4Layout.setVerticalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder12 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder12.setTitle("GRANDPARENTS (Spouse)");
        xPanel5.setBorder(xTitledBorder12);

        xPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mother's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder13 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder13.setTitle("Lolo");
        xFormPanel11.setBorder(xTitledBorder13);
        xFormPanel11.setCellspacing(10);
        xFormPanel11.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField11.setText("xLookupField7");
        xLookupField11.setCaption("First Name");
        xFormPanel11.add(xLookupField11);

        xTextField21.setText("xTextField13");
        xTextField21.setCaption("Middle Name");
        xFormPanel11.add(xTextField21);

        xTextField22.setText("xTextField14");
        xTextField22.setCaption("Last Name");
        xFormPanel11.add(xTextField22);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder14 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder14.setTitle("Lola (Maiden Name)");
        xFormPanel12.setBorder(xTitledBorder14);
        xFormPanel12.setCellspacing(10);
        xFormPanel12.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField12.setText("xLookupField7");
        xLookupField12.setCaption("First Name");
        xFormPanel12.add(xLookupField12);

        xTextField23.setText("xTextField13");
        xTextField23.setCaption("Middle Name");
        xFormPanel12.add(xTextField23);

        xTextField24.setText("xTextField14");
        xTextField24.setCaption("Last Name");
        xFormPanel12.add(xTextField24);

        javax.swing.GroupLayout xPanel6Layout = new javax.swing.GroupLayout(xPanel6);
        xPanel6.setLayout(xPanel6Layout);
        xPanel6Layout.setHorizontalGroup(
            xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        xPanel6Layout.setVerticalGroup(
            xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        xPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Father's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder15 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder15.setTitle("Lolo");
        xFormPanel13.setBorder(xTitledBorder15);
        xFormPanel13.setCellspacing(10);
        xFormPanel13.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField13.setText("xLookupField7");
        xLookupField13.setCaption("First Name");
        xFormPanel13.add(xLookupField13);

        xTextField25.setText("xTextField13");
        xTextField25.setCaption("Middle Name");
        xFormPanel13.add(xTextField25);

        xTextField26.setText("xTextField14");
        xTextField26.setCaption("Last Name");
        xFormPanel13.add(xTextField26);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder16 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder16.setTitle("Lola (Maiden Name)");
        xFormPanel14.setBorder(xTitledBorder16);
        xFormPanel14.setCellspacing(10);
        xFormPanel14.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField14.setText("xLookupField7");
        xLookupField14.setCaption("First Name");
        xFormPanel14.add(xLookupField14);

        xTextField27.setText("xTextField13");
        xTextField27.setCaption("Middle Name");
        xFormPanel14.add(xTextField27);

        xTextField28.setText("xTextField14");
        xTextField28.setCaption("Last Name");
        xFormPanel14.add(xTextField28);

        javax.swing.GroupLayout xPanel7Layout = new javax.swing.GroupLayout(xPanel7);
        xPanel7.setLayout(xPanel7Layout);
        xPanel7Layout.setHorizontalGroup(
            xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        xPanel7Layout.setVerticalGroup(
            xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout xPanel5Layout = new javax.swing.GroupLayout(xPanel5);
        xPanel5.setLayout(xPanel5Layout);
        xPanel5Layout.setHorizontalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel5Layout.setVerticalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 40, Short.MAX_VALUE))
                    .addGroup(xPanel1Layout.createSequentialGroup()
                        .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xFormPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xFormPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xFormPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(xPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        xScrollPane1.setViewportView(xPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel10;
    private com.rameses.rcp.control.XFormPanel xFormPanel11;
    private com.rameses.rcp.control.XFormPanel xFormPanel12;
    private com.rameses.rcp.control.XFormPanel xFormPanel13;
    private com.rameses.rcp.control.XFormPanel xFormPanel14;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XFormPanel xFormPanel8;
    private com.rameses.rcp.control.XFormPanel xFormPanel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField10;
    private com.rameses.rcp.control.XLookupField xLookupField11;
    private com.rameses.rcp.control.XLookupField xLookupField12;
    private com.rameses.rcp.control.XLookupField xLookupField13;
    private com.rameses.rcp.control.XLookupField xLookupField14;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XLookupField xLookupField5;
    private com.rameses.rcp.control.XLookupField xLookupField6;
    private com.rameses.rcp.control.XLookupField xLookupField7;
    private com.rameses.rcp.control.XLookupField xLookupField8;
    private com.rameses.rcp.control.XLookupField xLookupField9;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XPanel xPanel3;
    private com.rameses.rcp.control.XPanel xPanel4;
    private com.rameses.rcp.control.XPanel xPanel5;
    private com.rameses.rcp.control.XPanel xPanel6;
    private com.rameses.rcp.control.XPanel xPanel7;
    private com.rameses.rcp.control.XScrollPane xScrollPane1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField14;
    private com.rameses.rcp.control.XTextField xTextField15;
    private com.rameses.rcp.control.XTextField xTextField16;
    private com.rameses.rcp.control.XTextField xTextField17;
    private com.rameses.rcp.control.XTextField xTextField18;
    private com.rameses.rcp.control.XTextField xTextField19;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField20;
    private com.rameses.rcp.control.XTextField xTextField21;
    private com.rameses.rcp.control.XTextField xTextField22;
    private com.rameses.rcp.control.XTextField xTextField23;
    private com.rameses.rcp.control.XTextField xTextField24;
    private com.rameses.rcp.control.XTextField xTextField25;
    private com.rameses.rcp.control.XTextField xTextField26;
    private com.rameses.rcp.control.XTextField xTextField27;
    private com.rameses.rcp.control.XTextField xTextField28;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
