/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.appointment.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author pictd-training1
 */
@StyleSheet
@Template(CrudFormPage.class)
public class VerificationPage extends javax.swing.JPanel {

    /**
     * Creates new form PDSVerificationPage
     */
    public VerificationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xScrollPane1 = new com.rameses.rcp.control.XScrollPane();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField29 = new com.rameses.rcp.control.XTextField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField30 = new com.rameses.rcp.control.XTextField();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLookupField5 = new com.rameses.rcp.control.XLookupField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        xLookupField6 = new com.rameses.rcp.control.XLookupField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xTextField31 = new com.rameses.rcp.control.XTextField();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xPanel3 = new com.rameses.rcp.control.XPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField7 = new com.rameses.rcp.control.XLookupField();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField14 = new com.rameses.rcp.control.XTextField();
        xFormPanel8 = new com.rameses.rcp.control.XFormPanel();
        xLookupField8 = new com.rameses.rcp.control.XLookupField();
        xTextField15 = new com.rameses.rcp.control.XTextField();
        xTextField16 = new com.rameses.rcp.control.XTextField();
        xTextField32 = new com.rameses.rcp.control.XTextField();
        xPanel4 = new com.rameses.rcp.control.XPanel();
        xFormPanel9 = new com.rameses.rcp.control.XFormPanel();
        xLookupField9 = new com.rameses.rcp.control.XLookupField();
        xTextField17 = new com.rameses.rcp.control.XTextField();
        xTextField18 = new com.rameses.rcp.control.XTextField();
        xFormPanel10 = new com.rameses.rcp.control.XFormPanel();
        xLookupField10 = new com.rameses.rcp.control.XLookupField();
        xTextField19 = new com.rameses.rcp.control.XTextField();
        xTextField20 = new com.rameses.rcp.control.XTextField();
        xTextField33 = new com.rameses.rcp.control.XTextField();
        xPanel5 = new com.rameses.rcp.control.XPanel();
        xPanel6 = new com.rameses.rcp.control.XPanel();
        xFormPanel11 = new com.rameses.rcp.control.XFormPanel();
        xLookupField11 = new com.rameses.rcp.control.XLookupField();
        xTextField21 = new com.rameses.rcp.control.XTextField();
        xTextField22 = new com.rameses.rcp.control.XTextField();
        xFormPanel12 = new com.rameses.rcp.control.XFormPanel();
        xLookupField12 = new com.rameses.rcp.control.XLookupField();
        xTextField23 = new com.rameses.rcp.control.XTextField();
        xTextField24 = new com.rameses.rcp.control.XTextField();
        xTextField34 = new com.rameses.rcp.control.XTextField();
        xPanel7 = new com.rameses.rcp.control.XPanel();
        xFormPanel13 = new com.rameses.rcp.control.XFormPanel();
        xLookupField13 = new com.rameses.rcp.control.XLookupField();
        xTextField25 = new com.rameses.rcp.control.XTextField();
        xTextField26 = new com.rameses.rcp.control.XTextField();
        xFormPanel14 = new com.rameses.rcp.control.XFormPanel();
        xLookupField14 = new com.rameses.rcp.control.XLookupField();
        xTextField27 = new com.rameses.rcp.control.XTextField();
        xTextField28 = new com.rameses.rcp.control.XTextField();
        xTextField35 = new com.rameses.rcp.control.XTextField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Applicant's Name");
        xFormPanel2.setBorder(xTitledBorder1);
        xFormPanel2.setCaption("");
        xFormPanel2.setCellspacing(10);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField1.setCaption("First Name");
        xLookupField1.setExpression("#{item.firstname}");
        xLookupField1.setHandler("lookup:individualwide");
        xLookupField1.setName("entity.person"); // NOI18N
        xFormPanel2.add(xLookupField1);

        xTextField2.setCaption("Middle Name");
        xTextField2.setDepends(new String[] {"entity.person"});
        xTextField2.setName("entity.person.middlename"); // NOI18N
        xFormPanel2.add(xTextField2);

        xTextField1.setCaption("Last Name");
        xTextField1.setDepends(new String[] {"entity.person"});
        xTextField1.setName("entity.person.lastname"); // NOI18N
        xFormPanel2.add(xTextField1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Spouse's Name (Maiden Name)");
        xFormPanel3.setBorder(xTitledBorder2);
        xFormPanel3.setCellspacing(10);
        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField2.setCaption("First Name");
        xLookupField2.setExpression("#{item.firstname}");
        xLookupField2.setHandler("lookup:individualwide");
        xLookupField2.setName("entity.spouse"); // NOI18N
        xFormPanel3.add(xLookupField2);

        xTextField4.setCaption("Middle Name");
        xTextField4.setDepends(new String[] {"entity.spouse"});
        xTextField4.setInputFormat("");
        xTextField4.setName("entity.spouse.middlename"); // NOI18N
        xFormPanel3.add(xTextField4);

        xTextField3.setCaption("Last Name");
        xTextField3.setDepends(new String[] {"entity.spouse"});
        xTextField3.setName("entity.spouse.lastname"); // NOI18N
        xFormPanel3.add(xTextField3);

        xTextField29.setCaption("Maiden Name");
        xTextField29.setName("entity.spouse.maidenname"); // NOI18N
        xFormPanel3.add(xTextField29);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Father's Name");
        xFormPanel4.setBorder(xTitledBorder3);
        xFormPanel4.setCellspacing(10);
        xFormPanel4.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField3.setCaption("First Name");
        xLookupField3.setExpression("#{item.firstname}");
        xLookupField3.setHandler("lookup:individualwide");
        xLookupField3.setName("entity.father"); // NOI18N
        xFormPanel4.add(xLookupField3);

        xTextField6.setCaption("Middle Name");
        xTextField6.setDepends(new String[] {"entity.father"});
        xTextField6.setName("entity.father.middlename"); // NOI18N
        xFormPanel4.add(xTextField6);
        xTextField6.getAccessibleContext().setAccessibleDescription("");

        xTextField5.setCaption("Last Name");
        xTextField5.setDepends(new String[] {"entity.father"});
        xTextField5.setName("entity.father.lastname"); // NOI18N
        xFormPanel4.add(xTextField5);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Mother's Maiden Name");
        xFormPanel5.setBorder(xTitledBorder4);
        xFormPanel5.setCellspacing(10);
        xFormPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField4.setCaption("First Name");
        xLookupField4.setExpression("#{item.firstname}");
        xLookupField4.setHandler("lookup:individualwide");
        xLookupField4.setName("entity.mother"); // NOI18N
        xFormPanel5.add(xLookupField4);

        xTextField8.setCaption("Middle Name");
        xTextField8.setDepends(new String[] {"entity.mother"});
        xTextField8.setName("entity.mother.middlename"); // NOI18N
        xFormPanel5.add(xTextField8);

        xTextField7.setCaption("Last Name");
        xTextField7.setDepends(new String[] {"entity.mother"});
        xTextField7.setName("entity.mother.lastname"); // NOI18N
        xFormPanel5.add(xTextField7);

        xTextField30.setCaption("Maiden Name");
        xTextField30.setName("entity.mother.maidenname"); // NOI18N
        xTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField30ActionPerformed(evt);
            }
        });
        xFormPanel5.add(xTextField30);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder5 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder5.setTitle("Spouse's Father");
        xFormPanel6.setBorder(xTitledBorder5);
        xFormPanel6.setCellspacing(10);
        xFormPanel6.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField5.setCaption("First Name");
        xLookupField5.setExpression("#{item.firstname}");
        xLookupField5.setHandler("lookup:individualwide");
        xLookupField5.setName("entity.spousefather"); // NOI18N
        xLookupField5.setNullWhenEmpty(false);
        xFormPanel6.add(xLookupField5);

        xTextField9.setCaption("Middle Name");
        xTextField9.setDepends(new String[] {"entity.spousefather"});
        xTextField9.setName("entity.spousefather.middlename"); // NOI18N
        xFormPanel6.add(xTextField9);

        xTextField10.setCaption("Last Name");
        xTextField10.setDepends(new String[] {"entity.spousefather"});
        xTextField10.setName("entity.spousefather.lastname"); // NOI18N
        xFormPanel6.add(xTextField10);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder6 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder6.setTitle("Spouse's Mother (Maiden Name)");
        xFormPanel7.setBorder(xTitledBorder6);
        xFormPanel7.setCellspacing(10);
        xFormPanel7.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField6.setCaption("First Name");
        xLookupField6.setExpression("#{item.firstname}");
        xLookupField6.setHandler("lookup:individualwide");
        xLookupField6.setName("entity.spousemother"); // NOI18N
        xFormPanel7.add(xLookupField6);

        xTextField11.setCaption("Middle Name");
        xTextField11.setDepends(new String[] {"entity.spousemother"});
        xTextField11.setName("entity.spousemother.middlename"); // NOI18N
        xFormPanel7.add(xTextField11);

        xTextField12.setCaption("Last Name");
        xTextField12.setDepends(new String[] {"entity.spousemother"});
        xTextField12.setName("entity.spousemother.lastname"); // NOI18N
        xFormPanel7.add(xTextField12);

        xTextField31.setCaption("Maiden Name");
        xTextField31.setDepends(new String[] {"entity.spousemother"});
        xTextField31.setName("entity.spousemother.maidenname"); // NOI18N
        xTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField31ActionPerformed(evt);
            }
        });
        xFormPanel7.add(xTextField31);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder7 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder7.setTitle("GRANDPARENTS (Applicant)");
        xPanel2.setBorder(xTitledBorder7);

        xPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mother's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder8 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder8.setTitle("Lolo");
        xFormPanel1.setBorder(xTitledBorder8);
        xFormPanel1.setCellspacing(10);
        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField7.setCaption("First Name");
        xLookupField7.setExpression("#{item.firstname}");
        xLookupField7.setHandler("lookup:individualwide");
        xLookupField7.setName("entity.mothersidegrandfather"); // NOI18N
        xFormPanel1.add(xLookupField7);

        xTextField13.setCaption("Middle Name");
        xTextField13.setDepends(new String[] {"entity.mothersidegrandfather"});
        xTextField13.setName("entity.mothersidegrandfather.middlename"); // NOI18N
        xFormPanel1.add(xTextField13);

        xTextField14.setCaption("Last Name");
        xTextField14.setDepends(new String[] {"entity.mothersidegrandfather"});
        xTextField14.setName("entity.mothersidegrandfather.lastname"); // NOI18N
        xFormPanel1.add(xTextField14);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder9 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder9.setTitle("Lola (Maiden Name)");
        xFormPanel8.setBorder(xTitledBorder9);
        xFormPanel8.setCellspacing(10);
        xFormPanel8.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField8.setCaption("First Name");
        xLookupField8.setExpression("#{item.firstname}");
        xLookupField8.setHandler("lookup:individualwide");
        xLookupField8.setName("entity.mothersidegrandmother"); // NOI18N
        xFormPanel8.add(xLookupField8);

        xTextField15.setCaption("Middle Name");
        xTextField15.setDepends(new String[] {"entity.mothersidegrandmother"});
        xTextField15.setName("entity.mothersidegrandmother.middlename"); // NOI18N
        xFormPanel8.add(xTextField15);

        xTextField16.setCaption("Last Name");
        xTextField16.setDepends(new String[] {"entity.mothersidegrandmother"});
        xTextField16.setName("entity.mothersidegrandmother.lastname"); // NOI18N
        xFormPanel8.add(xTextField16);

        xTextField32.setCaption("Maiden Name");
        xTextField32.setDepends(new String[] {"entity.mothersidegrandmother"});
        xTextField32.setName("entity.spousemother.maidenname"); // NOI18N
        xTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField32ActionPerformed(evt);
            }
        });
        xFormPanel8.add(xTextField32);

        javax.swing.GroupLayout xPanel3Layout = new javax.swing.GroupLayout(xPanel3);
        xPanel3.setLayout(xPanel3Layout);
        xPanel3Layout.setHorizontalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xPanel3Layout.createSequentialGroup()
                        .addComponent(xFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        xPanel3Layout.setVerticalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        xPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Father's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder10 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder10.setTitle("Lolo");
        xFormPanel9.setBorder(xTitledBorder10);
        xFormPanel9.setCellspacing(10);
        xFormPanel9.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField9.setCaption("First Name");
        xLookupField9.setExpression("#{item.firstname}");
        xLookupField9.setHandler("lookup:individualwide");
        xLookupField9.setName("entity.fathersidegrandfather"); // NOI18N
        xFormPanel9.add(xLookupField9);

        xTextField17.setCaption("Middle Name");
        xTextField17.setDepends(new String[] {"entity.fathersidegrandfather"});
        xTextField17.setName("entity.fathersidegrandfather.middlename"); // NOI18N
        xFormPanel9.add(xTextField17);

        xTextField18.setCaption("Last Name");
        xTextField18.setDepends(new String[] {"entity.fathersidegrandfather"});
        xTextField18.setName("entity.fathersidegrandfather.lastname"); // NOI18N
        xFormPanel9.add(xTextField18);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder11 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder11.setTitle("Lola (Maiden Name)");
        xFormPanel10.setBorder(xTitledBorder11);
        xFormPanel10.setCellspacing(10);
        xFormPanel10.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField10.setCaption("First Name");
        xLookupField10.setExpression("#{item.firstname}");
        xLookupField10.setHandler("lookup:individualwide");
        xLookupField10.setName("entity.fathersidegrandmother"); // NOI18N
        xFormPanel10.add(xLookupField10);

        xTextField19.setCaption("Middle Name");
        xTextField19.setDepends(new String[] {"entity.fathersidegrandmother"});
        xTextField19.setName("entity.fathersidegrandmother.middlename"); // NOI18N
        xFormPanel10.add(xTextField19);

        xTextField20.setCaption("Last Name");
        xTextField20.setDepends(new String[] {"entity.fathersidegrandmother"});
        xTextField20.setName("entity.fathersidegrandmother.lastname"); // NOI18N
        xFormPanel10.add(xTextField20);

        xTextField33.setCaption("Maiden Name");
        xTextField33.setDepends(new String[] {"entity.fathersidegrandmother"});
        xTextField33.setName("entity.spousemother.maidenname"); // NOI18N
        xTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField33ActionPerformed(evt);
            }
        });
        xFormPanel10.add(xTextField33);

        javax.swing.GroupLayout xPanel4Layout = new javax.swing.GroupLayout(xPanel4);
        xPanel4.setLayout(xPanel4Layout);
        xPanel4Layout.setHorizontalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel4Layout.setVerticalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder12 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder12.setTitle("GRANDPARENTS (Spouse)");
        xPanel5.setBorder(xTitledBorder12);

        xPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mother's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder13 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder13.setTitle("Lolo");
        xFormPanel11.setBorder(xTitledBorder13);
        xFormPanel11.setCellspacing(10);
        xFormPanel11.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField11.setCaption("First Name");
        xLookupField11.setExpression("#{item.firstname}");
        xLookupField11.setHandler("lookup:individualwide");
        xLookupField11.setName("entity.spousemothersidegrandfather"); // NOI18N
        xFormPanel11.add(xLookupField11);

        xTextField21.setCaption("Middle Name");
        xTextField21.setDepends(new String[] {"entity.spousemothersidegrandfather"});
        xTextField21.setName("entity.spousemothersidegrandfather.middlename"); // NOI18N
        xFormPanel11.add(xTextField21);

        xTextField22.setCaption("Last Name");
        xTextField22.setDepends(new String[] {"entity.spousemothersidegrandfather"});
        xTextField22.setName("entity.spousemothersidegrandfather.lastname"); // NOI18N
        xFormPanel11.add(xTextField22);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder14 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder14.setTitle("Lola (Maiden Name)");
        xFormPanel12.setBorder(xTitledBorder14);
        xFormPanel12.setCellspacing(10);
        xFormPanel12.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField12.setCaption("First Name");
        xLookupField12.setExpression("#{item.firstname}");
        xLookupField12.setHandler("lookup:individualwide");
        xLookupField12.setName("entity.spousemothersidegrandmother"); // NOI18N
        xFormPanel12.add(xLookupField12);

        xTextField23.setCaption("Middle Name");
        xTextField23.setDepends(new String[] {"entity.spousemothersidegrandmother"});
        xTextField23.setName("entity.spousemothersidegrandmother.middlename"); // NOI18N
        xFormPanel12.add(xTextField23);

        xTextField24.setCaption("Last Name");
        xTextField24.setDepends(new String[] {"entity.spousemothersidegrandmother"});
        xTextField24.setName("entity.spousemothersidegrandmother.lastname"); // NOI18N
        xFormPanel12.add(xTextField24);

        xTextField34.setCaption("Maiden Name");
        xTextField34.setDepends(new String[] {"entity.spousemothersidegrandmother"});
        xTextField34.setName("entity.spousemother.maidenname"); // NOI18N
        xTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField34ActionPerformed(evt);
            }
        });
        xFormPanel12.add(xTextField34);

        javax.swing.GroupLayout xPanel6Layout = new javax.swing.GroupLayout(xPanel6);
        xPanel6.setLayout(xPanel6Layout);
        xPanel6Layout.setHorizontalGroup(
            xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel6Layout.setVerticalGroup(
            xPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        xPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Father's Side"));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder15 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder15.setTitle("Lolo");
        xFormPanel13.setBorder(xTitledBorder15);
        xFormPanel13.setCellspacing(10);
        xFormPanel13.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField13.setCaption("First Name");
        xLookupField13.setExpression("#{item.firstname}");
        xLookupField13.setHandler("lookup:individualwide");
        xLookupField13.setName("entity.spousefathersidegrandfather"); // NOI18N
        xFormPanel13.add(xLookupField13);

        xTextField25.setCaption("Middle Name");
        xTextField25.setDepends(new String[] {"entity.spousefathersidegrandfather"});
        xTextField25.setName("entity.spousefathersidegrandfather.middlename"); // NOI18N
        xFormPanel13.add(xTextField25);

        xTextField26.setCaption("Last Name");
        xTextField26.setDepends(new String[] {"entity.spousefathersidegrandfather"});
        xTextField26.setName("entity.spousefathersidegrandfather.lastname"); // NOI18N
        xFormPanel13.add(xTextField26);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder16 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder16.setTitle("Lola (Maiden Name)");
        xFormPanel14.setBorder(xTitledBorder16);
        xFormPanel14.setCellspacing(10);
        xFormPanel14.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField14.setCaption("First Name");
        xLookupField14.setExpression("#{item.firstname}");
        xLookupField14.setHandler("lookup:individualwide");
        xLookupField14.setName("entity.spousefathersidegrandmother"); // NOI18N
        xFormPanel14.add(xLookupField14);

        xTextField27.setCaption("Middle Name");
        xTextField27.setDepends(new String[] {"entity.spousefathersidegrandmother"});
        xTextField27.setName("entity.spousefathersidegrandmother.middlename"); // NOI18N
        xFormPanel14.add(xTextField27);

        xTextField28.setCaption("Last Name");
        xTextField28.setDepends(new String[] {"entity.spousefathersidegrandmother"});
        xTextField28.setName("entity.spousefathersidegrandmother.lastname"); // NOI18N
        xFormPanel14.add(xTextField28);

        xTextField35.setCaption("Maiden Name");
        xTextField35.setDepends(new String[] {"entity.spousefathersidegrandmother"});
        xTextField35.setName("entity.spousemother.maidenname"); // NOI18N
        xTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTextField35ActionPerformed(evt);
            }
        });
        xFormPanel14.add(xTextField35);

        javax.swing.GroupLayout xPanel7Layout = new javax.swing.GroupLayout(xPanel7);
        xPanel7.setLayout(xPanel7Layout);
        xPanel7Layout.setHorizontalGroup(
            xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel7Layout.setVerticalGroup(
            xPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout xPanel5Layout = new javax.swing.GroupLayout(xPanel5);
        xPanel5.setLayout(xPanel5Layout);
        xPanel5Layout.setHorizontalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel5Layout.setVerticalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(xPanel1Layout.createSequentialGroup()
                        .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(xPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, xPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(xSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(xPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(xFormPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xFormPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xFormPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xFormPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(xFormPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(xPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        xScrollPane1.setViewportView(xPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField30ActionPerformed

    private void xTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField31ActionPerformed

    private void xTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField32ActionPerformed

    private void xTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField33ActionPerformed

    private void xTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField34ActionPerformed

    private void xTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xTextField35ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel10;
    private com.rameses.rcp.control.XFormPanel xFormPanel11;
    private com.rameses.rcp.control.XFormPanel xFormPanel12;
    private com.rameses.rcp.control.XFormPanel xFormPanel13;
    private com.rameses.rcp.control.XFormPanel xFormPanel14;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XFormPanel xFormPanel8;
    private com.rameses.rcp.control.XFormPanel xFormPanel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField10;
    private com.rameses.rcp.control.XLookupField xLookupField11;
    private com.rameses.rcp.control.XLookupField xLookupField12;
    private com.rameses.rcp.control.XLookupField xLookupField13;
    private com.rameses.rcp.control.XLookupField xLookupField14;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XLookupField xLookupField5;
    private com.rameses.rcp.control.XLookupField xLookupField6;
    private com.rameses.rcp.control.XLookupField xLookupField7;
    private com.rameses.rcp.control.XLookupField xLookupField8;
    private com.rameses.rcp.control.XLookupField xLookupField9;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XPanel xPanel3;
    private com.rameses.rcp.control.XPanel xPanel4;
    private com.rameses.rcp.control.XPanel xPanel5;
    private com.rameses.rcp.control.XPanel xPanel6;
    private com.rameses.rcp.control.XPanel xPanel7;
    private com.rameses.rcp.control.XScrollPane xScrollPane1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField14;
    private com.rameses.rcp.control.XTextField xTextField15;
    private com.rameses.rcp.control.XTextField xTextField16;
    private com.rameses.rcp.control.XTextField xTextField17;
    private com.rameses.rcp.control.XTextField xTextField18;
    private com.rameses.rcp.control.XTextField xTextField19;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField20;
    private com.rameses.rcp.control.XTextField xTextField21;
    private com.rameses.rcp.control.XTextField xTextField22;
    private com.rameses.rcp.control.XTextField xTextField23;
    private com.rameses.rcp.control.XTextField xTextField24;
    private com.rameses.rcp.control.XTextField xTextField25;
    private com.rameses.rcp.control.XTextField xTextField26;
    private com.rameses.rcp.control.XTextField xTextField27;
    private com.rameses.rcp.control.XTextField xTextField28;
    private com.rameses.rcp.control.XTextField xTextField29;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField30;
    private com.rameses.rcp.control.XTextField xTextField31;
    private com.rameses.rcp.control.XTextField xTextField32;
    private com.rameses.rcp.control.XTextField xTextField33;
    private com.rameses.rcp.control.XTextField xTextField34;
    private com.rameses.rcp.control.XTextField xTextField35;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
